[env]
LOOM_PRJ_NAME = "loom"
LOOM_PRJ_QUALIFIER = "dev"
LOOM_PRJ_ORG = "taleroangel"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
