[env]
WEFTER_PRJ_NAME = "wefter"
WEFTER_PRJ_QUALIFIER = "dev"
WEFTER_PRJ_ORG = "taleroangel"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
